spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/no_country
spring.datasource.username=no_country
spring.datasource.password=asd123

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true